#!/usr/bin/env bash

# This is mainly for testing purposes, This will only run node under production under the context of this
# bash script.
function setProductionEnvironments {
    # Set environment as production
    echo "export NODE_ENV=production";
    export NODE_ENV=production

    # Set port as 3009
    echo "export PORT=3009"
    export PORT=3009
}

# Build webpack
function buildWebpackProduction {
    echo "Building webpack production config";

    echo "webpack --config webpack.production.config.js";
    webpack --config webpack.production.config.js
}

# Serve Webpack
function serveWebpackProduction {
    echo "Starting production server";

    echo "npm start";
    npm start
}

setProductionEnvironments
buildWebpackProduction
serveWebpackProduction
